# Deploy do site do Beiçola F.I
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:

      - name: Baixar arquivos do projeto
        uses: actions/checkout@v4

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Preparar arquivos do site
        run: |
          mkdir site
          cp -r src/* site/
          cp -r imagens site/

      - name: Enviar arquivos para o GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Publicar site
        id: deployment
        uses: actions/deploy-pages@v5
